Managing student and graduate records is of paramount importance, as it directly impacts the accuracy and security of essential academic information. Traditional record-keeping systems often encounter significant inefficiencies and are susceptible to various vulnerabilities, which can compromise data integrity. Consequently, there is an urgent need for the development and implementation of innovative digital verification methods. These advancements seek to improve the reliability, accessibility, and overall protection of academic records, ensuring they align with the demands of modern educational environments @VerificationofUniversityStudentandGraduateDatausingBlockchainTechnology.

In recent years, the issue of counterfeit diplomas and transcripts has gained considerable attention. In 2019, Nuril Furkan underscored the growing threat of fraudulent academic credentials—especially during general elections—emphasizing the urgent need for stringent verification processes @ElectronicDocumentAuthenticityVerificationofDiplomaAndTranscriptUsingSmartContractonEthereumBlockchain. Proactively addressing this issue allows universities to safeguard their academic integrity, enhance student learning experiences, and foster a culture of trust.

Blockchain technology, with its decentralized framework, ensures data integrity and immutability by employing robust cryptographic techniques, making it an ideal solution for secure transactions and reliable data management in education. This framework guarantees secure interactions and builds trust among participants in various digital ecosystem @BlockchainInEducationASystematicReviewAndPracticalCaseStudies.

Blockchain technology and IPFS offer a robust framework for decentralized and secure solutions, ensuring that certificate verification is both reliable and trustworthy, enhancing transparency for all users. IPFS provides a way to store data in a decentralized manner @9903549. While promising, IPFS also presents challenges that must be addressed in future implementations. By leveraging both blockchain and IPFS, the proposed system enhances security, decentralization, and user control over credentials.

Blockchain has evolved beyond cryptocurrencies, enabling innovative solutions in various industries and enhancing transparency and trust. Its applications extend to sectors like supply chain management and healthcare, owing to its inherent ability to securely store and manage data @AnOverviewoftheEmergingTechnologyBlockchain. This versatility positions blockchain as an ideal solution for applications demanding high levels of trust and transparency.

The InterPlanetary File System significantly boosts the safety and accessibility of digital credentials by utilizing decentralized storage, ensuring sensitive information is both protected and readily accessible to authorized users, as shown in @ipfs. Blockchain and IPFS improve data integrity by addressing vulnerabilities inherent in centralized systems and providing decentralized, cryptographically secure access controls, ensuring that sensitive information remains secure and trustworthy for all users @SecureFileSharingUsingBlockchainandIPFSwithSmartContract-BasedAccessControl.

#figure( 
  image("img/ipfs.png", width: 80%), 
  caption: [IPFS Distributed Network] 
)<ipfs>

This research comprehensively analyzes Blockchain and IPFS architectures, aiming to propose a robust framework designed to significantly enhance the security and reliability of academic data management and dissemination in the digital landscape.

In Indonesia, the online diploma verification system SIVIL was introduced in 2017 to combat the persistent issue of counterfeit diplomas and transcripts @ElectronicDocumentAuthenticityVerificationofDiplomaAndTranscriptUsingSmartContractonEthereumBlockchain. Despite these efforts, challenges remain, underscoring the need for continuous improvements in verification processes and greater public awareness regarding the authenticity of academic records.

Recent blockchain-based verification systems, such as those implemented by Kanan et al. at Al-Zaytoonah University and Cheng et al., demonstrate how this technology can streamline and secure academic credentialing, offering real-world evidence of its efficacy in reducing fraud risks @8717505 @8394455.